// GLOBALS.H
//
// Global Include file

#if !defined( GLOBALS_H )
#define GLOBALS_H

/******** Common Type Definitons ********/
// unsigned types
typedef unsigned char         Byte;
typedef unsigned short        UInt16;
typedef unsigned long         UInt32;
typedef unsigned long long    UInt64;
// signed types
typedef signed char           SByte;
typedef signed short          Int16;
typedef signed long           Int32;
typedef signed long long      Int64;

#endif