CC = wpp386
CL = wcl386
# the /zp1 flag forces structures to NEVER pad elements, so the layout of
# a structure will be EXACTLY as it appears in code
# the /q flag forces the compiler and linker to display less useless lines
# the /we flag treats all warnings as errors, after all we should strive for 0 compiler warnings
# the /l=dos4g flag forces the linker to generate code for DOS/4GW and embed
# the DOS/4GW runtime in the binary
CFLAGS = /zp1 /q /we
LDFLAGS = /l=dos4g /q

PROG = playmidi.exe
HDRS = midi.h globals.h opl3.h timer.h visual.h dpmi.h svga.h
SRCS = main.cpp midi.cpp opl3.cpp timer.cpp visual.cpp dpmi.cpp svga.cpp

OBJS = $(SRCS:.cpp=.obj)

$(PROG) : $(OBJS)
  $(CL) $(LDFLAGS) -fe=$(PROG) $(OBJS)

# define CPP compile behaviors (this is the argument called on all out-of-date .cpp files)
.cpp.obj:
  $(CC) $(CFLAGS) $*.cpp

# dependencies

main.obj : main.cpp midi.h globals.h opl3.h timer.h visual.h

midi.obj : midi.cpp midi.h globals.h opl3.h timer.h visual.h

opl3.obj : opl3.cpp opl3.h globals.h

timer.obj : timer.cpp timer.h globals.h

visual.obj : visual.cpp visual.h globals.h timer.h svga.h

dpmi.obj : dpmi.cpp dpmi.h globals.h

svga.obj : svga.cpp svga.h dpmi.h globals.h

# cleanup command (MAKE clean)
clean : .SYMBOLIC
  @if exist *.obj del *.obj
  @if exist *.err del *.err
  @if exist $(PROG) del $(PROG)
  @echo Build cleaned.